### ISSUE TITLE
spring-boot 示例概要

### ISSUE THREAD

**Issue by biezhi** [biezhi/spring-boot-examples#1]
1. Hello SpringBoot
2. 日志配置
3. 模板引擎/JSP配置
4. 拦截器配置
5. 全局异常处理
6. 国际化处理
7. 数据源配置
8. 事务管理
9. 服务注册和发现
10. 配置中心管理
11. ORM(Mybatis/JPA)
12. NOSQL使用(Redis/Mongo)
13. 分布式Session
14. 服务负载均衡(Ribbon)
15. 服务熔断器(断路器)
16. 服务超时以及其他处理
17. 任务调度
18. 消息队列
19. 权限控制(Apache Shiro/Spring Security)
20. OAuth认证

**Comment by baocaixiong** [comment]
初学java
问：

> 比如mvc-aop、mvc-interceptor里面只有一个pom文件表示是什么意思，待完成😂😂的意思吗？

**Comment by biezhi** [comment]
@baocaixiong 逐渐增加的，我先把项目结构建立好了
